### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-buildkit#293]
PHP 8.1 is leaving active support on 25 November 2023. We should update to PHP 8.2.

**Comment by rosiel** [comment]
This is to say, I'm tapping out - I can't install this, the stack is too complex.

**Comment by aOelschlager** [comment]
@nigelgbanks I started to try and tackle this maybe a month ago and everything seemed to build ok with the exception of crayfits. Here's my branch for it: https://github.com/aOelschlager/isle-buildkit/tree/php-8-2
This is the error I was seeing:  > [crayfits stage-0 4/7] RUN --mount=type=bind,source=rootfs/var/www/crayfits/composer.lock,target=/var/www/crayfits/composer.lock     composer install -d /var/www/crayfits &&     cleanup.sh:
0.571 /usr/local/bin/composer: line 9: php: command not found
------
Dockerfile:32
--------------------
  31 |     
  32 | >>> RUN --mount=type=bind,source=rootfs/var/www/crayfits/composer.lock,target=/var/www/crayfits/composer.lock \
  33 | >>>     composer install -d /var/www/crayfits && \
  34 | >>>     cleanup.sh
  35 |     
--------------------
ERROR: failed to solve: process "/bin/bash -euo pipefail -c composer install -d /var/www/crayfits &&     cleanup.sh" did not complete successfully: exit code: 127
make: *** [Makefile:195: bake] Error 1

I'm not going to pursue this further but I thought I would share what I ran into since you understand this stuff way better than I do.

**Comment by nigelgbanks** [comment]
Started a draft here https://github.com/Islandora-Devops/isle-buildkit/pull/299. I have to test to determine if a major version change is warranted or if a minor would suffice.

**Comment by nigelgbanks** [comment]
Hmm seems major is needed as this will break Drupal 9 installs
